//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_de_areas_de_figuras_soap.ServiceReferenceAreass {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAreass.servicio_web_areasSoap")]
    public interface servicio_web_areasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular_area_cuadrado", ReplyAction="*")]
        int Calcular_area_cuadrado(int lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular_area_cuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Calcular_area_cuadradoAsync(int lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular_area_triangulo", ReplyAction="*")]
        int Calcular_area_triangulo(int baser, int altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular_area_triangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Calcular_area_trianguloAsync(int baser, int altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular_area_circulo", ReplyAction="*")]
        double Calcular_area_circulo(double radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calcular_area_circulo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> Calcular_area_circuloAsync(double radio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicio_web_areasSoapChannel : Servicio_de_areas_de_figuras_soap.ServiceReferenceAreass.servicio_web_areasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicio_web_areasSoapClient : System.ServiceModel.ClientBase<Servicio_de_areas_de_figuras_soap.ServiceReferenceAreass.servicio_web_areasSoap>, Servicio_de_areas_de_figuras_soap.ServiceReferenceAreass.servicio_web_areasSoap {
        
        public servicio_web_areasSoapClient() {
        }
        
        public servicio_web_areasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicio_web_areasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicio_web_areasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicio_web_areasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Calcular_area_cuadrado(int lado) {
            return base.Channel.Calcular_area_cuadrado(lado);
        }
        
        public System.Threading.Tasks.Task<int> Calcular_area_cuadradoAsync(int lado) {
            return base.Channel.Calcular_area_cuadradoAsync(lado);
        }
        
        public int Calcular_area_triangulo(int baser, int altura) {
            return base.Channel.Calcular_area_triangulo(baser, altura);
        }
        
        public System.Threading.Tasks.Task<int> Calcular_area_trianguloAsync(int baser, int altura) {
            return base.Channel.Calcular_area_trianguloAsync(baser, altura);
        }
        
        public double Calcular_area_circulo(double radio) {
            return base.Channel.Calcular_area_circulo(radio);
        }
        
        public System.Threading.Tasks.Task<double> Calcular_area_circuloAsync(double radio) {
            return base.Channel.Calcular_area_circuloAsync(radio);
        }
    }
}
